const USER_AUTHORIZE = 'USER_SIGN_IN',
  USER_LOGOUT = 'USER_LOGOUT',
  FETCHING_LOADING = 'FETCHING_LOADING',
  USER_REFRESH = 'USER_REFRESH',
  UPDATE = 'UPDATE',
  SET_STRIP = 'SET_STRIP',
  FirstTimeShowNDONE = 'FirstTimeShowNDONE';
export default {
  UPDATE,
  USER_AUTHORIZE,
  USER_LOGOUT,
  FETCHING_LOADING,
  USER_REFRESH,
  SET_STRIP,
  FirstTimeShowNDONE,
};
